server:
  port: 9093


spring:
    application:
      name: USER-SERVICE
    datasource:
      url: jdbc:h2:mem:mydb
      username: sa
      password: password
      driverClassName: org.h2.Driver
      jpa:
        spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
      h2:
        console:
          enabled: true

eureka:
    client:
          register-with-eureka: true
          fetch-registry: true
          service-url:
            defaultZone: http://localhost:8761/eureka/
instance:
              hostname: localhost

